### ISSUE TITLE
Crash when press push notification on Android SDK 2.11.0

### ISSUE THREAD

**Issue by leegeunhyeok** [leegeunhyeok/react-native-zendesk-messaging#17]
**Describe the bug**

Crash when press push notification (on SDK 2.11.0, 2.8.0 is fine)

**To Reproduce**
1. App Launch (Zendesk.initialize here)
2. Receive Zendesk push notificaiton
3. Press push notification

**Expected behavior**

Open messaging view without any errors

**Screenshots**

`kotlin.UninitializedPropertyAccessException: lateinit property visibleScreenTracker has not been initialized`

![image](https://github.com/leegeunhyeok/react-native-zendesk-messaging/assets/26512984/25dcc49e-8020-46c3-92f2-ef676544b5cf)

```
2023-05-18 20:00:17.357  8745-8745  AndroidRuntime          com.Classting                        E  FATAL EXCEPTION: main
                                                                                                    Process: com.Classting, PID: 8745
                                                                                                    kotlin.UninitializedPropertyAccessException: lateinit property visibleScreenTracker has not been initialized
                                                                                                    	at zendesk.messaging.android.internal.conversationslistscreen.ConversationsListActivity.getVisibleScreenTracker(ConversationsListActivity.kt:53)
                                                                                                    	at zendesk.messaging.android.internal.conversationslistscreen.ConversationsListActivity.onStart(ConversationsListActivity.kt:130)
                                                                                                    	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
                                                                                                    	at android.app.Activity.performStart(Activity.java:8315)
                                                                                                    	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4060)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8663)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Environment (please complete the following information):**
 - Platform: Android
 - React Native Version: 0.70.6
 - Zendesk SDK Version 2.11.0

**Additional context**

**Comment by leegeunhyeok** [comment]
https://support.zendesk.com/hc/en-us/community/posts/5717388122138-Crash-when-press-push-notification-on-Android
