### ISSUE TITLE
Crash Release Version in Android

### ISSUE THREAD

**Issue by ajiehatajie** [leegeunhyeok/react-native-zendesk-messaging#8]
Android Release is Crash 
Ios not Crash

react native 0.71.7
zendeskSdkVersion = "2.11.0"

**Comment by leegeunhyeok** [comment]
Can I get crash logs?

**Comment by ajiehatajie** [comment]
Error in Firebase 

Fatal Exception: java.lang.NoSuchMethodError: No virtual method object()Lon/g; in class Lon/g; or its super classes (declaration of 'on.g' appears in /data/app/~~27II3m-pW9AcoJ78IoIUKA==/id.co.ssam.dev-G29clesdsSl-pliBcUtAig==/base.apk!classes2.dex)

at com.microsoft.appcenter.ingestion.models.json.DefaultLogSerializer.writeLog(DefaultLogSerializer.java)
       at com.microsoft.appcenter.ingestion.models.json.DefaultLogSerializer.serializeLog(DefaultLogSerializer.java:5)
       at com.microsoft.appcenter.persistence.DatabasePersistence.putLog(DatabasePersistence.java:44)
       at com.microsoft.appcenter.channel.DefaultChannel.enqueue(DefaultChannel.java:253)
       at com.microsoft.appcenter.AppCenter.sendStartServiceLog(AppCenter.java:53)
       at com.microsoft.appcenter.AppCenter.finishStartServices(AppCenter.java:255)
       at com.microsoft.appcenter.AppCenter.access$600(AppCenter.java)
       at com.microsoft.appcenter.AppCenter$7.run(AppCenter.java:8)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by ajiehatajie** [comment]
I think this error is because another library is in my project, when I made it from scratch it ran smoothly

**Comment by leegeunhyeok** [comment]
Are you using App center code push?

Same(or similar) issue was reported at code push repository.
(https://github.com/microsoft/react-native-code-push/issues/2399)
